// utils/countries.js
const countries = [
  { id: 1, name: "AFEGANISTÃO" },
  { id: 2, name: "ALBÂNIA" },
  { id: 161, name: "ARGÉLIA" },
  { id: 219, name: "SAMOA AMERICANA" },
  { id: 3, name: "ANDORRA" },
  { id: 220, name: "ANGOLA" },
  { id: 4, name: "ANGUILLA" },
  { id: 5, name: "ANTÍGUA E BARBUDA" },
  { id: 6, name: "ARGENTINA" },
  { id: 7, name: "ARMÊNIA" },
  { id: 450, name: "ARUBA" },
  { id: 451, name: "AUSTRÁLIA" },
  { id: 8, name: "ÁUSTRIA" },
  { id: 174, name: "AZERBAIJÃO" },
  { id: 9, name: "BAHAMAS" },
  { id: 175, name: "BAREIN" },
  { id: 176, name: "BANGLADESH" },
  { id: 10, name: "BARBADOS" },
  { id: 11, name: "BIELORRÚSSIA" },
  { id: 12, name: "BÉLGICA" },
  { id: 13, name: "BELIZE" },
  { id: 14, name: "BENIM" },
  { id: 15, name: "BERMUDAS" },
  { id: 177, name: "BUTÃO" },
  { id: 178, name: "BOLÍVIA" },
  { id: 16, name: "BÓSNIA E HERZEGOVINA" },
  { id: 17, name: "BOTSUANA" },
  { id: 452, name: "BRASIL" },
  { id: 18, name: "ILHAS VIRGENS BRITÂNICAS" },
  { id: 19, name: "BRUNEI" },
  { id: 20, name: "BULGÁRIA" },
  { id: 21, name: "BURQUINA FASO" },
  { id: 22, name: "BURUNDI" },
  { id: 23, name: "CAMBOJA" },
  { id: 24, name: "CAMARÕES" },
  { id: 453, name: "CANADÁ" },
  { id: 25, name: "CABO VERDE" },
  { id: 179, name: "ILHAS CAYMAN" },
  { id: 26, name: "REPÚBLICA CENTRO-AFRICANA" },
  { id: 27, name: "CHADE" },
  { id: 28, name: "CHILE" },
  { id: 165, name: "CHINA" },
  { id: 454, name: "ILHA DO NATAL" },
  { id: 455, name: "ILHAS COCOS (KEELING)" },
  { id: 197, name: "COLÔMBIA" },
  { id: 29, name: "COMORES" },
  { id: 30, name: "CONGO" },
  { id: 457, name: "CONGO, REPÚBLICA DO (BRAZZAVILLE)" },
  { id: 458, name: "ILHAS COOK" },
  { id: 32, name: "COSTA RICA" },
  { id: 33, name: "COSTA DO MARFIM" },
  { id: 34, name: "CROÁCIA" },
  { id: 35, name: "CUBA" },
  { id: 36, name: "CHIPRE" },
  { id: 223, name: "CHIPRE DO NORTE" },
  { id: 37, name: "REPÚBLICA TCHECA" },
  { id: 38, name: "TCHECOSLOVÁQUIA" },
  { id: 456, name: "REPÚBLICA DEMOCRÁTICA DO CONGO (KINSHASA)" },
  { id: 39, name: "DINAMARCA" },
  { id: 40, name: "DJIBUTI" },
  { id: 41, name: "DOMINICA" },
  { id: 459, name: "REPÚBLICA DOMINICANA" },
  { id: 224, name: "REPÚBLICA DOMINICANA" },
  { id: 42, name: "TIMOR-LESTE" },
  { id: 43, name: "EQUADOR" },
  { id: 171, name: "EGITO" },
  { id: 44, name: "EL SALVADOR" },
  { id: 45, name: "GUINÉ EQUATORIAL" },
  { id: 46, name: "ERITREIA" },
  { id: 47, name: "ESTÔNIA" },
  { id: 48, name: "ETIÓPIA" },
  { id: 484, name: "UNIÃO EUROPEIA" },
  { id: 460, name: "ILHAS MALVINAS" },
  { id: 225, name: "ILHAS MALVINAS" },
  { id: 461, name: "ILHAS FAROÉ" },
  { id: 180, name: "FIJI" },
  { id: 49, name: "FINLÂNDIA" },
  { id: 50, name: "FRANÇA" },
  { id: 226, name: "POLINÉSIA FRANCESA" },
  { id: 51, name: "GABÃO" },
  { id: 52, name: "GÂMBIA" },
  { id: 181, name: "GEÓRGIA" },
  { id: 53, name: "ALEMANHA" },
  { id: 182, name: "GANA" },
  { id: 54, name: "GIBRALTAR" },
  { id: 55, name: "GRÉCIA" },
  { id: 462, name: "GROENLÂNDIA" },
  { id: 56, name: "GRANADA" },
  { id: 57, name: "GUATEMALA" },
  { id: 58, name: "GUINÉ" },
  { id: 59, name: "GUINÉ-BISSAU" },
  { id: 60, name: "GUIANA" },
  { id: 228, name: "HAITI" },
  { id: 463, name: "SANTA SÉ" },
  { id: 61, name: "HONDURAS" },
  { id: 62, name: "HONG KONG" },
  { id: 63, name: "HUNGRIA" },
  { id: 64, name: "ISLÂNDIA" },
  { id: 163, name: "ÍNDIA" },
  { id: 166, name: "INDONÉSIA" },
  { id: 65, name: "IRÃ" },
  { id: 464, name: "IRÃ (REPÚBLICA ISLÂMICA DO)" },
  { id: 66, name: "IRAQUE" },
  { id: 67, name: "IRLANDA" },
  { id: 68, name: "ISRAEL" },
  { id: 69, name: "ITÁLIA" },
  { id: 183, name: "COSTA DO MARFIM" },
  { id: 70, name: "JAMAICA" },
  { id: 184, name: "JAPÃO" },
  { id: 185, name: "JORDÂNIA" },
  { id: 465, name: "CAZAQUISTÃO" },
  { id: 186, name: "CAZAQUISTÃO" },
  { id: 71, name: "QUÊNIA" },
  { id: 72, name: "QUIRIBATI" },
  { id: 466, name: "REPÚBLICA POPULAR DEMOCRÁTICA DA COREIA (COREIA DO NORTE)" },
  { id: 229, name: "REPÚBLICA DA COREIA (COREIA DO SUL)" },
  { id: 467, name: "REPÚBLICA DA COREIA (COREIA DO SUL)" },
  { id: 230, name: "KOSOVO" },
  { id: 187, name: "KUWAIT" },
  { id: 76, name: "QUIRGUIZISTÃO" },
  { id: 188, name: "QUIRGUIZISTÃO" },
  { id: 231, name: "LAOS" },
  { id: 77, name: "LAOS" },
  { id: 73, name: "LETÔNIA" },
  { id: 74, name: "LÍBANO" },
  { id: 232, name: "LESOTO" },
  { id: 75, name: "LIBÉRIA" },
  { id: 78, name: "LÍBIA" },
  { id: 233, name: "LÍBIA" },
  { id: 79, name: "LIECHTENSTEIN" },
  { id: 80, name: "LITUÂNIA" },
  { id: 81, name: "LUXEMBURGO" },
  { id: 82, name: "MACAU" },
  { id: 234, name: "MACEDÔNIA (ARYM)" },
  { id: 235, name: "MADAGASCAR" },
  { id: 236, name: "MALAWI" },
  { id: 83, name: "MALÁSIA" },
  { id: 84, name: "MALDIVAS" },
  { id: 85, name: "MALI" },
  { id: 237, name: "MALTA" },
  { id: 86, name: "MALTA" },
  { id: 87, name: "ILHAS MARSHALL" },
  { id: 238, name: "ILHAS MARSHALL" },
  { id: 88, name: "MAURITÂNIA" },
  { id: 89, name: "MAURÍCIO" },
  { id: 168, name: "MÉXICO" },
  { id: 90, name: "MICRONÉSIA" },
  { id: 239, name: "MICRONÉSIA" },
  { id: 91, name: "MOLDÁVIA" },
  { id: 92, name: "MÔNACO" },
  { id: 93, name: "MONGÓLIA" },
  { id: 240, name: "MONTENEGRO" },
  { id: 94, name: "MONTENEGRO" },
  { id: 241, name: "MONTSERRAT" },
  { id: 95, name: "MARROCOS" },
  { id: 96, name: "MOÇAMBIQUE" },
  { id: 188, name: "MYANMAR (BIRMÂNIA)" },
  { id: 97, name: "NAMÍBIA" },
  { id: 242, name: "NAMÍBIA" },
  { id: 189, name: "NEPAL" },
  { id: 98, name: "NEPAL" },
  { id: 243, name: "PAÍSES BAIXOS" },
  { id: 99, name: "PAÍSES BAIXOS" },
  { id: 100, name: "NOVA CALEDÔNIA" },
  { id: 101, name: "NOVA ZELÂNDIA" },
  { id: 102, name: "NICARÁGUA" },
  { id: 103, name: "NÍGER" },
  { id: 104, name: "NIGÉRIA" },
  { id: 244, name: "ILHAS MARIANAS DO NORTE" },
  { id: 468, name: "ILHAS MARIANAS DO NORTE" },
  { id: 105, name: "NORUEGA" },
  { id: 190, name: "OMÃ" },
  { id: 106, name: "OMÃ" },
  { id: 107, name: "PAQUISTÃO" },
  { id: 108, name: "PALAU" },
  { id: 109, name: "PANAMÁ" },
  { id: 110, name: "PAPUA-NOVA GUINÉ" },
  { id: 111, name: "PARAGUAI" },
  { id: 112, name: "PERU" },
  { id: 164, name: "FILIPINAS" },
  { id: 191, name: "FILIPINAS" },
  { id: 113, name: "POLÔNIA" },
  { id: 245, name: "PORTUGAL" },
  { id: 114, name: "PORTUGAL" },
  { id: 115, name: "QATAR" },
  { id: 116, name: "ROMÊNIA" },
  { id: 117, name: "FEDERAÇÃO RUSSA" },
  { id: 118, name: "RUANDA" },
  { id: 119, name: "SÃO CRISTÓVÃO E NÉVIS" },
  { id: 120, name: "SANTA LÚCIA" },
  { id: 121, name: "SÃO VICENTE E GRANADINAS" },
  { id: 469, name: "SAMOA" },
  { id: 122, name: "SÃO MARINO" },
  { id: 123, name: "SÃO TOMÉ E PRÍNCIPE" },
  { id: 470, name: "ARÁBIA SAUDITA" },
  { id: 124, name: "SENEGAL" },
  { id: 125, name: "SÉRVIA" },
  { id: 126, name: "SEYCHELLES" },
  { id: 127, name: "SERRA LEOA" },
  { id: 128, name: "CINGAPURA" },
  { id: 129, name: "SINT MAARTEN" },
  { id: 130, name: "ESLOVÁQUIA" },
  { id: 131, name: "ESLOVÊNIA" },
  { id: 132, name: "ILHAS SALOMÃO" },
  { id: 133, name: "SOMÁLIA" },
  { id: 134, name: "ÁFRICA DO SUL" },
  { id: 135, name: "ESPANHA" },
  { id: 471, name: "SRI LANKA" },
  { id: 136, name: "SUDÃO" },
  { id: 192, name: "SUDÃO DO SUL" },
  { id: 472, name: "SURINAME" },
  { id: 137, name: "SUAZILÂNDIA" },
  { id: 138, name: "SUÉCIA" },
  { id: 139, name: "SUÍÇA" },
  { id: 193, name: "REPÚBLICA ÁRABE DA SÍRIA" },
  { id: 140, name: "TAIWAN" },
  { id: 473, name: "TAIWAN, PROVÍNCIA DA CHINA" },
  { id: 141, name: "TAJIQUISTÃO" },
  { id: 142, name: "TANZÂNIA" },
  { id: 143, name: "TAILÂNDIA" },
  { id: 144, name: "TOGO" },
  { id: 145, name: "TONGA" },
  { id: 146, name: "TRINDADE E TOBAGO" },
  { id: 147, name: "TUNÍSIA" },
  { id: 148, name: "TURQUIA" },
  { id: 149, name: "TURQUEMENISTÃO" },
  { id: 194, name: "TUVALU" },
  { id: 150, name: "UGANDA" },
  { id: 151, name: "UCRÂNIA" },
  { id: 195, name: "EMIRADOS ÁRABES UNIDOS" },
  { id: 152, name: "REINO UNIDO" },
  { id: 153, name: "ESTADOS UNIDOS" },
  { id: 154, name: "URUGUAI" },
  { id: 474, name: "UZBEQUISTÃO" },
  { id: 155, name: "VANUATU" },
  { id: 156, name: "VENEZUELA" },
  { id: 157, name: "VIETNÃ" },
  { id: 158, name: "IÉMEN" },
  { id: 159, name: "ZÂMBIA" },
  { id: 160, name: "ZIMBÁBUE" }
];

export default countries;


